
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <title> SmartAdmin (AJAX)</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- #CSS Links -->
    <!-- Basic Styles -->
    <link rel="stylesheet" type="text/css" media="screen" href="/zftest/public/v1.6.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/zftest/public/v1.6.1/css/font-awesome.min.css">

    <!-- SmartAdmin Styles : Caution! DO NOT change the order -->
    <link rel="stylesheet" type="text/css" media="screen" href="/zftest/public/v1.6.1/css/smartadmin-production-plugins.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/zftest/public/v1.6.1/css/smartadmin-production.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/zftest/public/v1.6.1/css/smartadmin-skins.min.css">

    <!-- SmartAdmin RTL Support -->
    <link rel="stylesheet" type="text/css" media="screen" href="/zftest/public/v1.6.1/css/smartadmin-rtl.min.css">

    <!-- We recommend you use "your_style.css" to override SmartAdmin
         specific styles this will also ensure you retrain your customization with each SmartAdmin update.
    <link rel="stylesheet" type="text/css" media="screen" href="css/your_style.css"> -->

    <!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="/zftest/public/v1.6.1/css/demo.min.css"> -->

    <!-- #FAVICONS -->
    <link rel="shortcut icon" href="/zftest/public/v1.6.1/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/zftest/public/v1.6.1/img/favicon/favicon.ico" type="image/x-icon">

    <!-- #GOOGLE FONT -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- #APP SCREEN / ICONS -->
    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="/zftest/public/v1.6.1/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/zftest/public/v1.6.1/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/zftest/public/v1.6.1/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/zftest/public/v1.6.1/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="/zftest/public/v1.6.1/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="/zftest/public/v1.6.1/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="/zftest/public/v1.6.1/img/splash/iphone.png" media="screen and (max-device-width: 320px)">



    <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
        if (!window.jQuery) {
            document.write('<script src="/zftest/public/v1.6.1/js/libs/jquery-2.1.1.min.js"><\/script>');
        }
    </script>

    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script>
        if (!window.jQuery.ui) {
            document.write('<script src="/zftest/public/v1.6.1/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
        }
    </script>

    <!-- IMPORTANT: APP CONFIG -->
    <script src="/zftest/public/v1.6.1/js/app.config.js"></script>

    <!-- JS TOUCH : include this plugin for mobile drag / drop touch events-->
    <script src="/zftest/public/v1.6.1/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script>

    <!-- BOOTSTRAP JS -->
    <script src="/zftest/public/v1.6.1/js/bootstrap/bootstrap.min.js"></script>

    <!-- CUSTOM NOTIFICATION -->
    <script src="/zftest/public/v1.6.1/js/notification/SmartNotification.min.js"></script>

    <!-- JARVIS WIDGETS -->
    <script src="/zftest/public/v1.6.1/js/smartwidgets/jarvis.widget.min.js"></script>

    <!-- EASY PIE CHARTS -->
    <script src="/zftest/public/v1.6.1/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>

    <!-- SPARKLINES -->
    <script src="/zftest/public/v1.6.1/js/plugin/sparkline/jquery.sparkline.min.js"></script>

    <!-- JQUERY VALIDATE -->
    <script src="/zftest/public/v1.6.1/js/plugin/jquery-validate/jquery.validate.min.js"></script>

    <!-- JQUERY MASKED INPUT -->
    <script src="/zftest/public/v1.6.1/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

    <!-- JQUERY SELECT2 INPUT -->
    <script src="/zftest/public/v1.6.1/js/plugin/select2/select2.min.js"></script>

    <!-- JQUERY UI + Bootstrap Slider -->
    <script src="/zftest/public/v1.6.1/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>

    <!-- browser msie issue fix -->
    <script src="/zftest/public/v1.6.1/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

    <!-- FastClick: For mobile devices: you can disable this in app.js -->
    <script src="/zftest/public/v1.6.1/js/plugin/fastclick/fastclick.min.js"></script>

    <!--[if IE 8]>
    <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
    <![endif]-->

    <!-- Demo purpose only -->
    <!-- <script src="/zftest/public/v1.6.1/js/demo.min.js"></script> -->

    <!-- MAIN APP JS FILE -->
    <script src="/zftest/public/v1.6.1/js/app.min.js"></script>

    <!-- ENHANCEMENT PLUGINS : NOT A REQUIREMENT -->
    <!-- Voice command : plugin -->
    <script src="/zftest/public/v1.6.1/js/speech/voicecommand.min.js"></script>

    <!-- SmartChat UI : plugin -->
    <script src="/zftest/public/v1.6.1/js/smart-chat-ui/smart.chat.ui.min.js"></script>
    <script src="/zftest/public/v1.6.1/js/smart-chat-ui/smart.chat.manager.min.js"></script>



</head>

<!--

TABLE OF CONTENTS.

Use search to find needed section.

===================================================================

|  01. #CSS Links                |  all CSS links and file paths  |
|  02. #FAVICONS                 |  Favicon links and file paths  |
|  03. #GOOGLE FONT              |  Google font link              |
|  04. #APP SCREEN / ICONS       |  app icons, screen backdrops   |
|  05. #BODY                     |  body tag                      |
|  06. #HEADER                   |  header tag                    |
|  07. #PROJECTS                 |  project lists                 |
|  08. #TOGGLE LAYOUT BUTTONS    |  layout buttons and actions    |
|  09. #MOBILE                   |  mobile view dropdown          |
|  10. #SEARCH                   |  search field                  |
|  11. #NAVIGATION               |  left panel & navigation       |
|  12. #MAIN PANEL               |  main panel                    |
|  13. #MAIN CONTENT             |  content holder                |
|  14. #PAGE FOOTER              |  page footer                   |
|  15. #SHORTCUT AREA            |  dropdown shortcuts area       |
|  16. #PLUGINS                  |  all scripts and plugins       |

===================================================================

-->

<!-- #BODY -->
<!-- Possible Classes

    * 'smart-style-{SKIN#}'
    * 'smart-rtl'         - Switch theme mode to RTL
    * 'menu-on-top'       - Switch to top navigation (no DOM change required)
    * 'no-menu'			  - Hides the menu completely
    * 'hidden-menu'       - Hides the main menu but still accessable by hovering over left edge
    * 'fixed-header'      - Fixes the header
    * 'fixed-navigation'  - Fixes the main menu
    * 'fixed-ribbon'      - Fixes breadcrumb
    * 'fixed-page-footer' - Fixes footer
    * 'container'         - boxed layout mode (non-responsive: will not work with fixed-navigation & fixed-ribbon)
-->
<body class="">

<!-- #HEADER -->
<header id="header">
<div id="logo-group">

    <!-- PLACE YOUR LOGO HERE -->
    <span id="logo"> <img src="/zftest/public/v1.6.1/img/logo.png" alt="SmartAdmin"> </span>
    <!-- END LOGO PLACEHOLDER -->

    <!-- Note: The activity badge color changes when clicked and resets the number to 0
         Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
    <span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge"> 21 </b> </span>

    <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
    <div class="ajax-dropdown">

        <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
        <div class="btn-group btn-group-justified" data-toggle="buttons">
            <label class="btn btn-default">
                <input type="radio" name="activity" id="/zftest/public/v1.6.1/ajax/notify/mail.html">
                Msgs (14) </label>
            <label class="btn btn-default">
                <input type="radio" name="activity" id="/zftest/public/v1.6.1/ajax/notify/notifications.html">
                notify (3) </label>
            <label class="btn btn-default">
                <input type="radio" name="activity" id="/zftest/public/v1.6.1/ajax/notify/tasks.html">
                Tasks (4) </label>
        </div>

        <!-- notification content -->
        <div class="ajax-notifications custom-scroll">

            <div class="alert alert-transparent">
                <h4>Click a button to show messages here</h4>
                This blank page message helps protect your privacy, or you can show the first message here automatically.
            </div>

            <i class="fa fa-lock fa-4x fa-border"></i>

        </div>
        <!-- end notification content -->

        <!-- footer: refresh area -->
					<span> Last updated on: 12/12/2013 9:43AM
						<button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                            <i class="fa fa-refresh"></i>
                        </button> </span>
        <!-- end footer -->

    </div>
    <!-- END AJAX-DROPDOWN -->
</div>

<!-- #PROJECTS: projects dropdown -->
<div class="project-context hidden-xs">

    <span class="label">Projects:</span>
    <span class="project-selector dropdown-toggle" data-toggle="dropdown">Recent projects <i class="fa fa-angle-down"></i></span>

    <!-- Suggestion: populate this list with fetch and push technique -->
    <ul class="dropdown-menu">
        <li>
            <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
        </li>
        <li>
            <a href="javascript:void(0);">Notes on pipeline upgradee</a>
        </li>
        <li>
            <a href="javascript:void(0);">Assesment Report for merchant account</a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
        </li>
    </ul>
    <!-- end dropdown-menu-->

</div>
<!-- end projects dropdown -->

<!-- #TOGGLE LAYOUT BUTTONS -->
<!-- pulled right: nav area -->
<div class="pull-right">

    <!-- collapse menu button -->
    <div id="hide-menu" class="btn-header pull-right">
        <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
    </div>
    <!-- end collapse menu -->

    <!-- #MOBILE -->
    <!-- Top menu profile link : this shows only when top menu is active -->
    <ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
        <li class="">
            <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
                <img src="/zftest/public/v1.6.1/img/avatars/sunny.png" alt="John Doe" class="online" />
            </a>
            <ul class="dropdown-menu pull-right">
                <li>
                    <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#ajax/profile.html" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> <u>P</u>rofile</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <u>S</u>hortcut</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <u>S</u>creen</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="/zftest/public/v1.6.1/login.html" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><u>L</u>ogout</strong></a>
                </li>
            </ul>
        </li>
    </ul>

    <!-- logout button -->
    <div id="logout" class="btn-header transparent pull-right">
        <span> <a href="/zftest/public/v1.6.1/login.html" title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser"><i class="fa fa-sign-out"></i></a> </span>
    </div>
    <!-- end logout button -->

    <!-- search mobile button (this is hidden till mobile view port) -->
    <div id="search-mobile" class="btn-header transparent pull-right">
        <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
    </div>
    <!-- end search mobile button -->

    <!-- #SEARCH -->
    <!-- input: search field -->
    <form action="#ajax/search.html" class="header-search pull-right">
        <input id="search-fld" type="text" name="param" placeholder="Find reports and more">
        <button type="submit">
            <i class="fa fa-search"></i>
        </button>
        <a href="javascript:void(0);" id="cancel-search-js" title="Cancel Search"><i class="fa fa-times"></i></a>
    </form>
    <!-- end input: search field -->

    <!-- fullscreen button -->
    <div id="fullscreen" class="btn-header transparent pull-right">
        <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
    </div>
    <!-- end fullscreen button -->

    <!-- #Voice Command: Start Speech -->
    <!-- NOTE: Voice command button will only show in browsers that support it. Currently it is hidden under mobile browsers.
               You can take off the "hidden-sm" and "hidden-xs" class to display inside mobile browser-->
    <div id="speech-btn" class="btn-header transparent pull-right hidden-sm hidden-xs">
        <div>
            <a href="javascript:void(0)" title="Voice Command" data-action="voiceCommand"><i class="fa fa-microphone"></i></a>
            <div class="popover bottom"><div class="arrow"></div>
                <div class="popover-content">
                    <h4 class="vc-title">Voice command activated <br><small>Please speak clearly into the mic</small></h4>
                    <h4 class="vc-title-error text-center">
                        <i class="fa fa-microphone-slash"></i> Voice command failed
                        <br><small class="txt-color-red">Must <strong>"Allow"</strong> Microphone</small>
                        <br><small class="txt-color-red">Must have <strong>Internet Connection</strong></small>
                    </h4>
                    <a href="javascript:void(0);" class="btn btn-success" onclick="commands.help()">See Commands</a>
                    <a href="javascript:void(0);" class="btn bg-color-purple txt-color-white" onclick="$('#speech-btn .popover').fadeOut(50);">Close Popup</a>
                </div>
            </div>
        </div>
    </div>
    <!-- end voice command -->

    <!-- multiple lang dropdown : find all flags in the flags page -->
    <ul class="header-dropdown-list hidden-xs">
        <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-us" alt="United States"> <span> US</span> <i class="fa fa-angle-down"></i> </a>
            <ul class="dropdown-menu pull-right">
                <li class="active">
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-us" alt="United States"> English (US)</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-fr" alt="France"> Français</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-es" alt="Spanish"> Español</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-de" alt="German"> Deutsch</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-jp" alt="Japan"> ???</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-cn" alt="China"> ??</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-it" alt="Italy"> Italiano</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-pt" alt="Portugal"> Portugal</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-ru" alt="Russia"> ??????? ????</a>
                </li>
                <li>
                    <a href="javascript:void(0);"><img src="/zftest/public/v1.6.1/img/blank.gif" class="flag flag-kr" alt="Korea"> ???</a>
                </li>

            </ul>
        </li>
    </ul>
    <!-- end multiple lang -->

</div>
<!-- end pulled right: nav area -->

</header>
<!-- END HEADER -->

<!-- #NAVIGATION -->
<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS/SASS variables -->
<aside id="left-panel">

<!-- User info -->
<div class="login-info">
				<span> <!-- User image size is adjusted inside CSS, it should stay as is -->

					<a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
                        <img src="/zftest/public/v1.6.1/img/avatars/sunny.png" alt="me" class="online" />
						<span>
							john.doe
						</span>
                        <i class="fa fa-angle-down"></i>
                    </a>

				</span>
</div>
<!-- end user info -->

<!-- NAVIGATION : This navigation is also responsive

To make this navigation dynamic please make sure to link the node
(the reference to the nav > ul) after page load. Or the navigation
will not initialize.
-->
<nav>
<!--
NOTE: Notice the gaps after each icon usage <i></i>..
Please note that these links work a bit different than
traditional href="" links. See documentation for details.
-->

<ul>
<li class="">
    <a href="/zftest/public/v1.6.1/ajax/dashboard.html" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span></a>
</li>
<li class="">
    <a href="/zftest/department" title="Setups"><i class="fa fa-lg fa-fw fa-user"></i>
        <span class="menu-item-parent">Setups</span></a>
</li>
<li>
    <a href="/zftest/public/v1.6.1/ajax/inbox.html"><i class="fa fa-lg fa-fw fa-inbox"></i> <span class="menu-item-parent">Inbox</span><span class="badge pull-right inbox-badge">14</span></a>
</li>
<li>
    <a href="#"><i class="fa fa-lg fa-fw fa-bar-chart-o"></i> <span class="menu-item-parent">Graphs</span></a>
    <ul>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/flot.html">Flot Chart</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/morris.html">Morris Charts</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/inline-charts.html">Inline Charts</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/dygraphs.html">Dygraphs</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/chartjs.html">Chart.js <span class="badge pull-right inbox-badge bg-color-yellow">new</span></a>
        </li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-lg fa-fw fa-table"></i> <span class="menu-item-parent">Tables</span></a>
    <ul>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/table.html">Normal Tables</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/datatables.html">Data Tables <span class="badge inbox-badge bg-color-greenLight">v1.10.6</span></a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/jqgrid.html">Jquery Grid</a>
        </li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-lg fa-fw fa-pencil-square-o"></i> <span class="menu-item-parent">Forms</span></a>
    <ul>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/form-elements.html">Smart Form Elements</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/form-templates.html">Smart Form Layouts</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/validation.html">Smart Form Validation</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/bootstrap-forms.html">Bootstrap Form Elements</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/bootstrap-validator.html">Bootstrap Form Validation</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/plugins.html">Form Plugins</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/wizard.html">Wizards</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/other-editors.html">Bootstrap Editors</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/dropzone.html">Dropzone</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/image-editor.html">Image Cropping <span class="badge pull-right inbox-badge bg-color-yellow">new</span></a>
        </li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-lg fa-fw fa-desktop"></i> <span class="menu-item-parent">UI Elements</span></a>
    <ul>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/general-elements.html">General Elements</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/buttons.html">Buttons</a>
        </li>
        <li>
            <a href="#">Icons</a>
            <ul>
                <li>
                    <a href="/zftest/public/v1.6.1/ajax/fa.html"><i class="fa fa-plane"></i> Font Awesome</a>
                </li>
                <li>
                    <a href="/zftest/public/v1.6.1/ajax/glyph.html"><i class="glyphicon glyphicon-plane"></i> Glyph Icons</a>
                </li>
                <li>
                    <a href="/zftest/public/v1.6.1/ajax/flags.html"><i class="fa fa-flag"></i> Flags</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/grid.html">Grid</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/treeview.html">Tree View</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/nestable-list.html">Nestable Lists</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/jqui.html">JQuery UI</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/typography.html">Typography</a>
        </li>
        <li>
            <a href="#">Six Level Menu</a>
            <ul>
                <li>
                    <a href="#"><i class="fa fa-fw fa-folder-open"></i> Item #2</a>
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-folder-open"></i> Sub #2.1 </a>
                            <ul>
                                <li>
                                    <a href="#"><i class="fa fa-fw fa-file-text"></i> Item #2.1.1</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-fw fa-plus"></i> Expand</a>
                                    <ul>
                                        <li>
                                            <a href="#"><i class="fa fa-fw fa-file-text"></i> File</a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="fa fa-fw fa-trash-o"></i> Delete</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-folder-open"></i> Item #3</a>

                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-folder-open"></i> 3ed Level </a>
                            <ul>
                                <li>
                                    <a href="#"><i class="fa fa-fw fa-file-text"></i> File</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-fw fa-file-text"></i> File</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" class="inactive"><i class="fa fa-fw fa-folder-open"></i> Item #4 (disabled)</a>
                </li>

            </ul>
        </li>
    </ul>
</li>
<li>
    <a href="/zftest/public/v1.6.1/ajax/calendar.html"><i class="fa fa-lg fa-fw fa-calendar"><em>3</em></i> <span class="menu-item-parent">Calendar</span></a>
</li>
<li>
    <a href="/zftest/public/v1.6.1/ajax/widgets.html"><i class="fa fa-lg fa-fw fa-list-alt"></i> <span class="menu-item-parent">Widgets</span></a>
</li>
<li>
    <a href="#"><i class="fa fa-lg fa-fw fa-puzzle-piece"></i> <span class="menu-item-parent">App Views</span></a>
    <ul>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/projects.html"><i class="fa fa-file-text-o"></i> Projects</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/blog.html"><i class="fa fa-paragraph"></i> Blog</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/gallery.html"><i class="fa fa-picture-o"></i> Gallery</a>
        </li>
        <li>
            <a href="#"><i class="fa fa-comments"></i> Forum Layout</a>
            <ul>
                <li><a href="/zftest/public/v1.6.1/ajax/forum.html">General View</a></li>
                <li><a href="/zftest/public/v1.6.1/ajax/forum-topic.html">Topic View</a></li>
                <li><a href="/zftest/public/v1.6.1/ajax/forum-post.html">Post View</a></li>
            </ul>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/profile.html"><i class="fa fa-group"></i> Profile</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/timeline.html"><i class="fa fa-clock-o"></i> Timeline</a>
        </li>
    </ul>
</li>
<li>
    <a href="/zftest/public/v1.6.1/ajax/gmap-xml.html"><i class="fa fa-lg fa-fw fa-map-marker"></i> <span class="menu-item-parent">GMap Skins</span><span class="badge bg-color-greenLight pull-right inbox-badge">9</span></a>
</li>
<li>
    <a href="#"><i class="fa fa-lg fa-fw fa-windows"></i> <span class="menu-item-parent">Miscellaneous</span></a>
    <ul>
        <li>
            <a href="http://bootstraphunter.com/smartadmin-landing/" target="_blank">Landing Page <i class="fa fa-external-link"></i></a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/pricing-table.html">Pricing Tables</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/invoice.html">Invoice</a>
        </li>
        <li>
            <a href="login.html" target="_top">Login</a>
        </li>
        <li>
            <a href="register.html" target="_top">Register</a>
        </li>
        <li>
            <a href="lock.html" target="_top">Locked Screen</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/error404.html">Error 404</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/error500.html">Error 500</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/blank_.html">Blank Page</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/email-template.html">Email Template</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/search.html">Search Page</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/ckeditor.html">CK Editor</a>
        </li>
    </ul>
</li>
<li class="top-menu-invisible">
    <a href="#"><i class="fa fa-lg fa-fw fa-cube txt-color-blue"></i> <span class="menu-item-parent">SmartAdmin Intel</span></a>
    <ul>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/difver.html"><i class="fa fa-stack-overflow"></i> Different Versions</a>
        </li>
        <li>
            <a href="/zftest/public/v1.6.1/ajax/applayout.html"><i class="fa fa-cube"></i> App Settings</a>
        </li>
        <li>
            <a href="http://192.241.236.31/smartadmin/BUGTRACK/track_/documentation/index.html" target="_blank"><i class="fa fa-book"></i> Documentation</a>
        </li>
        <li>
            <a href="http://192.241.236.31/smartadmin/BUGTRACK/track_/" target="_blank"><i class="fa fa-bug"></i> Bug Tracker</a>
        </li>
        <li>
            <a href="http://myorange.ca/supportforum/" target="_blank"><i class="fa fa-wechat"></i> SmartAdmin Support</a>
        </li>
    </ul>
</li>
<li class="chat-department top-menu-invisible">
    <a href="#"><i class="fa fa-lg fa-fw fa-comment-o"><em class="bg-color-pink flash animated">!</em></i> <span class="menu-item-parent">Smart Chat API <sup>beta</sup></span></a>
    <ul>
        <li>
            <!-- DISPLAY USERS -->
            <div class="display-department">

                <input class="form-control chat-user-filter" placeholder="Filter" type="text">

                <a href="#" class="usr"
                   data-chat-id="cha1"
                   data-chat-fname="Sadi"
                   data-chat-lname="Orlaf"
                   data-chat-status="busy"
                   data-chat-alertmsg="Sadi Orlaf is in a meeting. Please do not disturb!"
                   data-chat-alertshow="true"
                   data-rel="popover-hover"
                   data-placement="right"
                   data-html="true"
                   data-content="
											<div class='usr-card'>
												<img src='img/avatars/5.png' alt='Sadi Orlaf'>
												<div class='usr-card-content'>
													<h3>Sadi Orlaf</h3>
													<p>Marketing Executive</p>
												</div>
											</div>
										">
                    <i></i>Sadi Orlaf
                </a>

                <a href="#" class="usr"
                   data-chat-id="cha2"
                   data-chat-fname="Jessica"
                   data-chat-lname="Dolof"
                   data-chat-status="online"
                   data-chat-alertmsg=""
                   data-chat-alertshow="false"
                   data-rel="popover-hover"
                   data-placement="right"
                   data-html="true"
                   data-content="
											<div class='usr-card'>
												<img src='img/avatars/1.png' alt='Jessica Dolof'>
												<div class='usr-card-content'>
													<h3>Jessica Dolof</h3>
													<p>Sales Administrator</p>
												</div>
											</div>
										">
                    <i></i>Jessica Dolof
                </a>

                <a href="#" class="usr"
                   data-chat-id="cha3"
                   data-chat-fname="Zekarburg"
                   data-chat-lname="Almandalie"
                   data-chat-status="online"
                   data-rel="popover-hover"
                   data-placement="right"
                   data-html="true"
                   data-content="
											<div class='usr-card'>
												<img src='img/avatars/3.png' alt='Zekarburg Almandalie'>
												<div class='usr-card-content'>
													<h3>Zekarburg Almandalie</h3>
													<p>Sales Admin</p>
												</div>
											</div>
										">
                    <i></i>Zekarburg Almandalie
                </a>

                <a href="#" class="usr"
                   data-chat-id="cha4"
                   data-chat-fname="Barley"
                   data-chat-lname="Krazurkth"
                   data-chat-status="away"
                   data-rel="popover-hover"
                   data-placement="right"
                   data-html="true"
                   data-content="
											<div class='usr-card'>
												<img src='img/avatars/4.png' alt='Barley Krazurkth'>
												<div class='usr-card-content'>
													<h3>Barley Krazurkth</h3>
													<p>Sales Director</p>
												</div>
											</div>
										">
                    <i></i>Barley Krazurkth
                </a>

                <a href="#" class="usr offline"
                   data-chat-id="cha5"
                   data-chat-fname="Farhana"
                   data-chat-lname="Amrin"
                   data-chat-status="incognito"
                   data-rel="popover-hover"
                   data-placement="right"
                   data-html="true"
                   data-content="
											<div class='usr-card'>
												<img src='img/avatars/female.png' alt='Farhana Amrin'>
												<div class='usr-card-content'>
													<h3>Farhana Amrin</h3>
													<p>Support Admin <small><i class='fa fa-music'></i> Playing Beethoven Classics</small></p>
												</div>
											</div>
										">
                    <i></i>Farhana Amrin (offline)
                </a>

                <a href="#" class="usr offline"
                   data-chat-id="cha6"
                   data-chat-fname="Lezley"
                   data-chat-lname="Jacob"
                   data-chat-status="incognito"
                   data-rel="popover-hover"
                   data-placement="right"
                   data-html="true"
                   data-content="
											<div class='usr-card'>
												<img src='img/avatars/male.png' alt='Lezley Jacob'>
												<div class='usr-card-content'>
													<h3>Lezley Jacob</h3>
													<p>Sales Director</p>
												</div>
											</div>
										">
                    <i></i>Lezley Jacob (offline)
                </a>

                <a href="/zftest/public/v1.6.1/ajax/chat.html" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">About the API</a>

            </div>
            <!-- END DISPLAY USERS -->
        </li>
    </ul>
</li>
</ul>
</nav>
<span class="minifyme" data-action="minifyMenu"> <i class="fa fa-arrow-circle-left hit"></i> </span>

</aside>
<!-- END NAVIGATION -->

<!-- #MAIN PANEL -->
<div id="main" role="main">

<!-- RIBBON -->
<div id="ribbon">

				<span class="ribbon-button-alignment">
					<span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true" data-reset-msg="Would you like to RESET all your saved widgets and clear LocalStorage?"><i class="fa fa-refresh"></i></span>
				</span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <!-- This is auto generated -->
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right" style="margin-right:25px">
        <a href="#" id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa fa-grid"></i> Change Grid</a>
        <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa fa-plus"></i> Add</span>
        <button id="search" class="btn btn-ribbon" data-title="search"><i class="fa fa-search"></i> <span class="hidden-mobile">Search</span></button>
    </span> -->

</div>
<!-- END RIBBON -->

<!-- #MAIN CONTENT -->
<div id="content">

<div class="row">
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
        <h1 class="page-title txt-color-blueDark">
            <i class="fa fa-table fa-fw "></i>
            Table
			<span>>
				Data Tables
			</span>
        </h1>
    </div>
    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
        <ul id="sparks" class="">
            <li class="sparks-info">
                <h5> My Income <span class="txt-color-blue">$47,171</span></h5>

                <div class="sparkline txt-color-blue hidden-mobile hidden-md hidden-sm">
                    1300, 1877, 2500, 2577, 2000, 2100, 3000, 2700, 3631, 2471, 2700, 3631, 2471
                </div>
            </li>
            <li class="sparks-info">
                <h5> Site Traffic <span class="txt-color-purple"><i class="fa fa-arrow-circle-up"
                                                                    data-rel="bootstrap-tooltip" title="Increased"></i>&nbsp;45%</span>
                </h5>

                <div class="sparkline txt-color-purple hidden-mobile hidden-md hidden-sm">
                    110,150,300,130,400,240,220,310,220,300, 270, 210
                </div>
            </li>
            <li class="sparks-info">
                <h5> Site Orders <span class="txt-color-greenDark"><i class="fa fa-shopping-cart"></i>&nbsp;2447</span>
                </h5>

                <div class="sparkline txt-color-greenDark hidden-mobile hidden-md hidden-sm">
                    110,150,300,130,400,240,220,310,220,300, 270, 210
                </div>
            </li>
        </ul>
    </div>
</div>

<!-- widget grid -->
<section id="widget-grid" class="page page-ui-tables">

    <!-- row -->
    <div class="row">

        <!-- NEW WIDGET START -->
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">



            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget jarviswidget-color-blueDark panel panel-lined table-responsive panel-hovered mb20 data-table " id="widGrid" data-widget-editbutton="false"
                 data-widget-colorbutton="false"
                 data-widget-editbutton="false"
                 data-widget-togglebutton="false"
                 data-widget-deletebutton="false"
                 data-widget-fullscreenbutton="false"
                 data-widget-custombutton="false"
                 role="widget" style=""

                >
                <!-- widget options:
                                usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                                data-widget-colorbutton="false"
                                data-widget-editbutton="false"
                                data-widget-togglebutton="false"
                                data-widget-deletebutton="false"
                                data-widget-fullscreenbutton="false"
                                data-widget-custombutton="false"
                                data-widget-collapsed="true"
                                data-widget-sortable="false"

                                -->
                <header>
                    <span class="widget-icon"> <i class="fa fa-table"></i> </span>

                    <h2>Setups List</h2>


                    <div class="widget-toolbar">

                        <div class="btn-group">
                            <button id="btnNew" class="btn dropdown-toggle btn-xs btn-primary" data-toggle="dropdown"><i
                                    class="fa fa-plus"></i> New
                            </button>
                        </div>
                    </div>

                </header>

                <!-- widget div-->
                <div>

                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->

                    </div>
                    <!-- end widget edit box -->

                    <!-- widget content -->
                    <di class="dataTables_wrapper no-footer">

                        <table id="tblMasterList" class="table table-striped table-bordered table-hover responsive-table" width="100%">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>City</th>

                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>

                    </div>
                    <!-- end widget content -->


                </div>
                <!-- end widget div -->

            </div>
            <!-- end widget -->
            <div class="jarviswidget hide panel panel-default panel-hovered panel-stacked mb30" id="widForm"
                 data-widget-colorbutton="false"
                 data-widget-editbutton="false"
                 data-widget-togglebutton="false"
                 data-widget-deletebutton="false"
                 data-widget-fullscreenbutton="false"
                 data-widget-custombutton="false"
                 role="widget" style=""
                 xmlns="http://www.w3.org/1999/html">

                <header>

                    <span class="widget-icon"> <i class="glyphicon glyphicon-stats txt-color-darken"></i> </span>

                    <h2>Department Info :</h2>

                    <div class="widget-toolbar" style="">

                    </div>

                </header>

                <!-- widget div-->
                <div class="no-padding">
                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        Username
                    </div>
                    <!-- end widget edit box -->

                    <div class="widget-body">

                        <!-- content -->

                        <div class="widget-toolbar" style="padding-right: 10px;padding-left: 10px">
                            <a id="btnBack" href="javascript:void(0);" class="btn btn-xs btn-default"><i
                                    class="fa fa-arrow-left"></i> <span
                                    class="hidden-mobile hidden-tablet">Back</span> </a>
                            <button id="btnSave" type="submit" class="btn btn-xs btn-success"><i class="fa fa-save"></i>
                                <strong><span
                                        class="hidden-mobile hidden-tablet">Save</span> </strong></button>

                        </div>
                        <ul class="nav nav-tabs  in" id="myTabMaster">
                            <li class="active">
                                <a data-toggle="tab" href="#general"><i class="fa fa-lg fa-info-circle"></i> <span
                                        class="hidden-mobile hidden-tablet">General</span></a>
                            </li>
                        </ul>

                        <div id="myTabContent" class="tab-content">
                            <div class="tab-pane fade active in padding-10 no-padding-bottom" id="general">
                                <form id="frmForm" class="smart-form" novalidate="novalidate" enctype="multipart/form-data">
                                    <fieldset style="padding-top: 5px">
                                        <div class="row">


                                            <section class="col col-2">
                                                <label class="label"><strong class="txt-color-blue">Ref No : </strong><i
                                                        id="id-RefNo">ISS/234/123123</i></label>
                                            </section>

                                            <section class="col col-4">
                                                <label class="label"><strong class="txt-color-blue">Name</strong></label>
                                                <label class="input"> <i class="  "></i>
                                                    <input type="text" id="name" name="name" class=" ">
                                                </label>
                                            </section>
                                            <section class="col col-4">
                                                <label class="label"><strong class="txt-color-blue">City</strong></label>
                                                <label class="input"> <i class=" "></i>
                                                    <input type="text" id="city" name="city" class=" ">
                                                </label>
                                            </section>


                                        </div>


                            </div>

                            </fieldset>
                            </form>
                        </div>
                        <!-- end general tab pane -->

                    </div>

                    <!-- Start All tab pane -->

                    <!-- End All tab pane -->

                    <!-- end content -->
                </div>

            </div>
            <!-- end widget div -->


        </article>
        <!-- WIDGET END -->

    </div>

    <!-- end row -->

    <!-- end row -->

</section>
<!-- end widget grid -->






<!--  Include Global JS Files -->
<script type="text/javascript" src="public/global_js/events.js"></script><script type="text/javascript" src="public/global_js/variables.js"></script>
<script type="text/javascript" src="public/global_js/events.js"></script>

<script type="text/javascript">


    $(document).ready(function () {


    });


    // PAGE RELATED SCRIPTS

    // pagefunction
    var pagefunction = function () {
        //console.log("cleared");

        /* // DOM Position key index //

         l - Length changing (dropdown)
         f - Filtering input (search)
         t - The Table! (datatable)
         i - Information (records)
         p - Pagination (paging)
         r - pRocessing
         < and > - div elements
         <"#id" and > - div with an id
         <"class" and > - div with a class
         <"#id.class" and > - div with an id and class

         Also see: http://legacy.datatables.net/usage/features
         */

        /* BASIC ;*/
        var responsiveHelper_dt_basic = undefined;
        var responsiveHelper_datatable_fixed_column = undefined;
        var responsiveHelper_datatable_col_reorder = undefined;
        var responsiveHelper_datatable_tabletools = undefined;

        var breakpointDefinition = {
            tablet: 1024,
            phone: 480
        };

        /* TABLETOOLS */
        oTableFindProduct = $("#tblMasterList").dataTable(
            {
                "bAutoWidth": false,
                "bLengthChange": false,
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "bProcessing": true,
                "bServerSide": true,
                "fnServerParams": function (aoData) {
                    aoData.push({ "name": "ProductType", "value": "" });
                },
                "sAjaxSource": "/zftest/department/list",
                "aoColumns": [
                    { "bSearchable": false, "bVisible": false },
                    null,
                    null
                ]
            });

        /* END TABLETOOLS */

    };

</script>

</div>

<!-- END #MAIN CONTENT -->

</div>
<!-- END #MAIN PANEL -->

<!-- #PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">SmartAdmin 1.6 <span class="hidden-xs"> - Web Application Framework</span> © 2014-2015</span>
        </div>

        <div class="col-xs-6 col-sm-6 text-right hidden-xs">
            <div class="txt-color-white inline-block">
                <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i>
                <div class="btn-group dropup">
                    <button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
                        <i class="fa fa-link"></i> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right text-left">
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Server Load</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li >
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Memory Load <span class="text-danger">*critical*</span></p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <button class="btn btn-block btn-default">refresh</button>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- end btn-group-->
            </div>
            <!-- end div-->
        </div>
        <!-- end col -->
    </div>
    <!-- end row -->
</div>
<!-- END FOOTER -->

<!-- #SHORTCUT AREA : With large tiles (activated via clicking user name tag)
     Note: These tiles are completely responsive, you can add as many as you like -->
<div id="shortcut">
    <ul>
        <li>
            <a href="#ajax/inbox.html" class="jarvismetro-tile big-cubes bg-color-blue"> <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span> </a>
        </li>
        <li>
            <a href="#ajax/calendar.html" class="jarvismetro-tile big-cubes bg-color-orangeDark"> <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span> </a>
        </li>
        <li>
            <a href="#ajax/gmap-xml.html" class="jarvismetro-tile big-cubes bg-color-purple"> <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span> </a>
        </li>
        <li>
            <a href="#ajax/invoice.html" class="jarvismetro-tile big-cubes bg-color-blueDark"> <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span> </a>
        </li>
        <li>
            <a href="#ajax/gallery.html" class="jarvismetro-tile big-cubes bg-color-greenLight"> <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span> </a>
        </li>
        <li>
            <a href="#ajax/profile.html" class="jarvismetro-tile big-cubes selected bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span> </a>
        </li>
    </ul>
</div>
<!-- END SHORTCUT AREA -->

<!--================================================== -->

<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)
<script data-pace-options='{ "restartOnRequestAfter": true }' src="js/plugin/pace/pace.min.js"></script>-->


<script type="application/javascript">


    /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // department widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

    pageSetUp();

    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     *
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     *
     */

    // load related plugins
    loadScript("/zftest/public/v1.6.1/js/plugin/datatables/jquery.dataTables.min.js", function(){
        loadScript("/zftest/public/v1.6.1/js/plugin/datatables/dataTables.colVis.min.js", function(){
            loadScript("/zftest/public/v1.6.1/js/plugin/datatables/dataTables.tableTools.min.js", function(){
                loadScript("/zftest/public/v1.6.1/js/plugin/datatables/dataTables.bootstrap.min.js", function(){
                    loadScript("/zftest/public/v1.6.1/js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)
                });
            });
        });
    });

</script>

</body>

</html>