<style>
.panel-heading .help
{
	font-size:22px;
	color:#0998cd;
	margin-left:10px;
	cursor:pointer;
	
}
.dt-toolbar
{
	display:none;
}
small {
  color: #FF414E;
  margin-top: 5px;
}
.error {
  border-color: #FF414E;
}
</style><!-- widget grid -->
<section id="widget-grid" class="page page-ui-tables">
    <!-- row -->
    <div class="row">
        <!-- NEW WIDGET START -->
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
           <?php include_once("form.php"); ?>
            <?php include_once("grid.php"); ?>
        </article>
        <!-- WIDGET END -->
    </div>
    <!-- end row -->
    <!-- end row -->
</section>
<!-- end widget grid -->
<script type="text/javascript">
    $(document).ready(function () {
		acl_PRINT=0;
        $("#btnSave").click(function (e) {
            e.stopPropagation();
            $("#frmForm").submit();
        });
		function setErrorMsg(field,msg)
		{
			$('#'+field).addClass('error');
			$('#'+field).parent().find("small").text(msg);
		}
        $("#frmForm").validate(
            {
                submitHandler: function (form) {
					
					var required = false;
					$('#frmForm small').text('');
					$('#frmForm').find('input,select').removeClass('error');
					
                    if ($("#notes").val() == '') {
                       required = true;
					   setErrorMsg('notes','This field is required');
                    }
					if ($("#color_code").val() == '') {
                       required = true;
					   setErrorMsg('color_code','This field is required');
                    }
					
					
                    if(strActionMode=="ADD") {
                        //Validate  duplicate
                        var isDuplicate = fn_validate_duplicate($("#notes").val(), "tbl_internal_notes", "notes", "<?php echo $this->url('internalnotes', array('action'=>'validateduplicate'));?>");
                        if (isDuplicate) {
                           
                            required = true;
							setErrorMsg('notes','Internal Note is Already exists');
                        }
					
                    }
                    if(required)
						return;
					
                    var $form = $('#frmForm');
                    var objMasterData = $form.serializeObject();
                    if (strActionMode == 'ADD')
                        $.extend(objMasterData, { MASTER_KEY_ID: 0});
                    else
                        $.extend(objMasterData, { MASTER_KEY_ID: iActiveID});
                    objMasterData = JSON.stringify(objMasterData);
                    var objFormData =
                    {
                        pAction    : strActionMode,
                        FORM_DATA: objMasterData
                    };
                    var objMyPost = AJAX_Post("<?php echo $this->url('internalnotes', array('action'=>'save'));?>", objFormData);
                    if (objMyPost.ERR_NO === 0) {
                        if (objMyPost.DATA.DBStatus === 'OK') {
                            strActionMode = "ADD";
							 clearForm("frmForm");
                            mySmallAlert('Save Record', 'Internal Note Saved successfully', 1);
                            iActiveID = objMyPost.DATA.MY_ID;
                           // visibleControl('widForm', false);
                            //visibleControl('widGrid', true);
                            oTable.fnDraw();
                        }
                    }
                    else {
                        mySmallAlert('Error...!', 'There was an error', 0);
                    }
                }
            });
    });
   
    var pagefunction = function () {
        
        var responsiveHelper_dt_basic = undefined;
        var responsiveHelper_datatable_fixed_column = undefined;
        var responsiveHelper_datatable_col_reorder = undefined;
        var responsiveHelper_datatable_tabletools = undefined;
        var breakpointDefinition = {
            tablet: 1024,
            phone: 480
        };
		var deleteact=acl_DELETE;
        /* TABLETOOLS */
        oTable = $("#tblMasterList").dataTable(
            {
                "bAutoWidth": false,
                "bLengthChange": false,
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<''p>>",
                "bProcessing": true,
                "bServerSide": true,
                "autoWidth" : true,
                "preDrawCallback" : function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#tblMasterList'), breakpointDefinition);
                    }
					//$('#tblMasterList_wrapper').parent().append(skeletonDiv);
					//$("#tblMasterListLoader").show();
					//$("#tblMasterList_wrapper").hide(); // hide datatable wrapper
                },
                "rowCallback" : function(nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback" : function(oSettings) {
                    responsiveHelper_dt_basic.respond();
					
					
					//$('#tblMasterList_wrapper,#tblMasterList').show();
					//$('#tblMasterListLoader').remove();
                },
                "fnServerParams": function (aoData) {
                    aoData.push({ "name": "id", "value": "" });
                },
                "sAjaxSource": "<?php echo $this->url('internalnotes', array('action'=>'list'));?>",
                "aoColumns": [
                    { "bSearchable": false, "bVisible": false },
                    
					
                    null,
                    null,
					
					{"bSearchable": false, "bSortable": false,
                        "mRender" : function (data, type, full) {
							
							var action_button = '<div style="white-space:nowrap;"><button type="button" class="btn btn-default btn-xs btn-list edit" row-id="'+full[0]+'"><span class="glyphicon glyphicon-pencil"></span>Edit</button><button type="button" class="btn btn-default btn-xs btn-list delete" row-id="'+full[0]+'"><span class="glyphicon glyphicon-trash"></span>Delete</button></div>';
                            return action_button;
                        }
                    }
					
                    
                ],
                "columnDefs": [
                    { className: "hidden", "targets": [ 0 ] }
                ]
            });
        /* END TABLETOOLS */
		$('.dataTables_filter input').attr("placeholder", "Search");
		
		//$(".dataTables_filter label").addClass('right');
        //fnEdit("<?php echo $this->url('internalnotes', array('action'=>'getrec'));?>");
        //fnView("<?php echo $this->url('internalnotes', array('action'=>'getrec'));?>");
        //fnDelete("<?php echo $this->url('internalnotes', array('action'=>'delete'));?>");
		
		
        var strUrl = "<?php echo $this->url('internalnotes', array('action'=>'getrec'));?>";
        //Function Used for Edit
        oTable.delegate('button.edit', 'click', function (e) {
            e.preventDefault();
           
            iActiveID = $(this).attr("row-id");
			
            //empty the form fields
            clearForm("frmForm");
            cPopulateEditEntries(iActiveID, strUrl);
            glbControlEnable(true);
        });
        oTable.delegate('button.delete', 'click', function (e) {
            e.preventDefault();
            iActiveID = $(this).attr("row-id");
			$.SmartMessageBox({
				title  : "Alert!",
				content: "Are you sure you want to delete this internal notes?",
				buttons: '[Yes][No]'
			}, function (ButtonPressed) {
				if (ButtonPressed === "Yes") {
					var objFormData =
					{
						pAction: 'DELETE',
						KEY_ID : iActiveID
					};
					var objMyPost = AJAX_Post("<?php echo $this->url('internalnotes', array('action'=>'delete'));?>", objFormData);
					if (objMyPost.ERR_NO === 0) {
						if (objMyPost.DATA.DBStatus === 'OK') {
							oTable.fnDraw();
							
							mySmallAlert('Success', 'Internal Note Deleted successfully', 1);
						}
						
						else {
							mySmallAlert('Error...!', 'There was an error', 0);
						}
					}
				}
				if (ButtonPressed === "No") {
				}
			});
        });
    };
</script>
<script>
    // load Page related plugins
                loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/jquery.dataTables.min.js", function () {
                    loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.colVis.min.js", function () {
                        loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.tableTools.min.js", function () {
                            loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.bootstrap.min.js", function () {
                                loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)
                            });
                        });
        });
    });
	
	//------------------- populate edit entries-----------------------------------------------------------------------------
    function cPopulateEditEntries(iID,strURL) {
        iActiveID = iID;
        var arrForms=[]; // Keep Form Values
        var strElementType; // Keep element type
        var objFormData =
        {
            pAction: 'GETREC',
            KEY_ID : iActiveID
        };
        var objMyPost = AJAX_Post(strURL, objFormData);
		
        if (objMyPost.ERR_NO === 0) {
            if (objMyPost.DATA.DBStatus === 'OK') {
               // visibleControl('widForm', true);
                //visibleControl('widGrid', false);
                strActionMode = 'EDIT';
                //populate master Records
                arrForms=objMyPost.DATA.data[0];
                $.each( arrForms, function( key, value ) { 
                    if ($("#"+key).length > 0) {  // check if exists or not
                        strElementType= $("#"+key).attr("type");
					
                        if(strElementType == "hidden") {  // if textbox
                            $("#" + key).val(value);
                            $("#spanRefNo").html(value);
                        }
                        else  if(strElementType == "text") {  // if textbox
                            $("#" + key).val(value);
                        }
						 else  if(strElementType == "color") {  // if textbox
                            $("#" + key).val(value);
                        }
						else  if(strElementType == "number") {  // if textbox
                            $("#" + key).val(value);
                        }
						else  if(strElementType == "password") {  // if textbox
                            $("#" + key).val(value);
                        }
                        else if($("#"+key).attr("name") == "descriptions") {  // if textarea
                            $("textarea#"+key).text(value);
                        }
                        else if(strElementType == "select") {  // if Select Box							
                            $("#" + key).select2("val",value);
                        }
                        else if(strElementType == "multiselect") {  // if Select Box with multi select
                            var arrValues = $.parseJSON(stripslashes(value));
                            $("#" + key).select2("val", arrValues);
                        }
                    }
                });
				
            }
        }
        else {
            mySmallAlert('Error...!', 'There was an error', 0);
        }
    }
</script>