<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <title >Prime Digital Arena - Dashboard Login</title>
    <meta name="description" content="">
    <meta name="author" content="">
	<meta property="og:title" content="Prime Digital Arena" />
	  <meta property="og:image" content="<?php echo $this->basePath(); ?>/public/img/p.svg" />
	  <meta property="og:url" content="https://www.primebackstage.in" />
	  <meta property="og:type" content="website" />
	  <meta property="og:image:width" content="1200" />
	  <meta property="og:image:height" content="630" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="stylesheet" type="text/css" media="screen"
          href="<?php echo $this->basePath(); ?>/public/css/selfAsserted.css">      

   

    <!-- #FAVICONS-->
    <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/public/img/p.svg"
          type="image/x-icon">
    <link rel="icon" href="<?php echo $this->basePath(); ?>/public/img/p.svg" type="image/x-icon">

    <!-- #GOOGLE FONT -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&amp;display=swap" rel="stylesheet">


    <link rel="apple-touch-icon"
          href="<?php echo $this->basePath(); ?>/public/img/p.svg">
    <link rel="apple-touch-icon" sizes="76x76"
          href="<?php echo $this->basePath(); ?>/public/img/p.svg">
    <link rel="apple-touch-icon" sizes="120x120"
          href="<?php echo $this->basePath(); ?>/public/img/p.svg">
    <link rel="apple-touch-icon" sizes="152x152"
          href="<?php echo $this->basePath(); ?>/public/img/p.svg">

	 <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image"
          href="<?php echo $this->basePath(); ?>/public/img/p.svg"
          media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image"
          href="<?php echo $this->basePath(); ?>/public/img/p.svg"
          media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="<?php echo $this->basePath(); ?>/public/img/p.svg"
          media="screen and (max-device-width: 320px)">

    <style>
        .select2-hidden-accessible { display:none; }
		body{background-color:#fff;}
		.smart-form fieldset {padding:0px !important;}
		.smart-form footer{    padding: 7px 0px 15px;}
		.smart-form section{margin-bottom:0px !important;}
		.select2-container .select2-choice {
			height: 34px !important;
			border: 1px solid #9b9bff!important;
			border-radius: 5px!important;
			
		}
		.divMessageBox {
  width: 100%;
  height: 100%;
  position: fixed;
  top: 0;
  left: 0;
  background: rgba(0, 0, 0, .6);
  z-index: 100000;
}
.SmallBox
		{
			width: auto;
			white-space: nowrap;
			color: #fff;
			z-index: 9999;
			overflow: hidden;
			border: 1px solid transparent;
			border-left: 5px solid #238d23;
			margin-left: -210px;
			position: fixed;
			bottom: 30px;
			right: 16px;
			padding: 12px 0px;
			background: #1f2937 !important;
			color: #fff;
			border-radius: 10px;
			font-size: 14px;
			z-index: 1000;
		}
.MessageBoxContainer {
  top: 35%;
  color: #fff;
  position: relative;
  width: 100%;
  background-color: #232323;
  background-color: rgba(0, 0, 0, .8);
  padding: 20px;
}
.MessageBoxMiddle {
  position: relative;
  left: 20%;
  width: 60%;
}
.MessageBoxMiddle .MsgTitle {
  letter-spacing: -1px;
  font-size: 24px;
  font-weight: 300;
}
.MessageBoxMiddle .pText {
  font-size: 13px;
}
.MessageBoxButtonSection {
  width: 100%;
  height: 30px;
}
/*.SmallBox {
  position: fixed;
  left: 50%;
  top: 95px;
  width: 420px;
  color: #fff;
  z-index: 9999;
  overflow: hidden;
  border: 1px solid transparent;
  margin-left: -210px;
}
.SmallBox:hover {
  border: 1px solid #fff;
  cursor: pointer;
}*/
.SmallBox .foto {
  font-size: 50px;
  position: absolute;
  left: 17px;
  display: none;
}
.SmallBox .textoFoto {
  width: 78%;
  margin: 3px 20px 3px 20px;
  float: left;
}
.SmallBox span {
  font-size: 17px;
  font-weight: 300;
  letter-spacing: -1px;
  display: block;
  margin: 4px 0;
  display: none;
}
.SmallBox p {
  font-size: 13px;
  margin-top: 2px;
  margin-bottom: 2px;
}
.SmallBox .fa {
  font-size: 52px;
}
    </style>
</head>
<body>


   
    <script>
        if (!window.jQuery) {
            document.write('<script src="<?php echo $this->basePath();?>/public/v1.6.1/js/libs/jquery-2.1.1.min.js"><\/script>');
        }
    </script>

    <!-- <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script> -->
    <script>
        if (!window.jQuery.ui) {
            document.write('<script src="<?php echo $this->basePath();?>/public/v1.6.1/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
        }
    </script>

    <!-- IMPORTANT: APP CONFIG -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/app.config.js"></script>

    <!-- JS TOUCH : include this plugin for mobile drag / drop touch events-->
    <script
        src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script>

    <!-- BOOTSTRAP JS -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/bootstrap/bootstrap.min.js"></script>

    <!-- CUSTOM NOTIFICATION -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/notification/SmartNotification.min.js"></script>

    <!-- JARVIS WIDGETS -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/smartwidgets/jarvis.widget.min.js"></script>

    <!-- EASY PIE CHARTS -->
    <script
        src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>

    <!-- SPARKLINES -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/sparkline/jquery.sparkline.min.js"></script>

    <!-- JQUERY VALIDATE -->
    <script
        src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/jquery-validate/jquery.validate.min.js"></script>

    <!-- JQUERY MASKED INPUT -->
    <script
        src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

    <!-- JQUERY SELECT2 INPUT -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/select2/select2.min.js"></script>

    <!-- JQUERY UI + Bootstrap Slider -->
    <script
        src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>

    <!-- browser msie issue fix -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

    <!-- FastClick: For mobile devices: you can disable this in app.js -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/fastclick/fastclick.min.js"></script>

    <!--[if IE 8]>
    <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
    <![endif]-->

    <!-- Demo purpose only -->
   <!-- <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/demo.min.js"></script>-->

    <!-- MAIN APP JS FILE -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/app.min.js"></script>

    <!-- ENHANCEMENT PLUGINS : NOT A REQUIREMENT -->
    <!-- Voice command : plugin -->
    <script src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/speech/voicecommand.min.js"></script>

  

    <!-- Plugins End -->


    <!-- #MAIN CONTENT -->

    <?php echo $this->content; ?>
    <!-- END #MAIN CONTENT -->

</div>
<!-- END #MAIN PANEL -->





<!--================================================== -->

<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)
<script data-pace-options='{ "restartOnRequestAfter": true }' src="<?php echo $this->basePath(); ?>/public/v1.6.1/js/plugin/pace/pace.min.js"></script>-->

</body>

</html>


<script src="<?php echo $this->basePath(); ?>/public/global_js/variables.js"></script>
<script src="<?php echo $this->basePath(); ?>/public/global_js/events.js"></script>
<script src="<?php echo $this->basePath(); ?>/public/global_js/functions.js"></script>

<script>

    //Load Common JS
    /*loadScript("<?php echo $this->basePath();?>/public/global_js/variables.js", function () {
        loadScript("<?php echo $this->basePath();?>/public/global_js/events.js", function () {
            loadScript("<?php echo $this->basePath();?>/public/global_js/functions.js", function () {
            });
            });
            });
    */
//Common Page Setup
    pageSetUp();
</script>
