<style ="text/css">

	.widget-body{

		padding-left:22px;

		padding-right:22px;

	}

	.columnappliedstl

	{

		padding-top:15px;

		padding-bottom:20px;

		border:1px solid #CCCCCC;

		

	}

	.rowappliedstl

	{

		max-width:100%;

		margin-bottom:20px;

				

	}

	.liappliedsizestl

	{

		font-size:55px;

	}

	.ulappliedstl

	{

		text-align:center;

	}

	.list_heading{

		width:100px;

		font-size:15px;

		font-weight:bold;

		text-transform:uppercase;

		

		

	}

	

</style>

<!-- widget grid -->

<section id="widget-grid" class="page page-ui-tables">

<div class="page-wrap">

    <!-- row -->

    <div class="row">



        <!-- NEW WIDGET START -->

        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">







            <!-- Widget ID (each widget will need unique ID)-->

<div class="jarviswidget jarviswidget-color-blueDark panel panel-lined table-responsive panel-hovered mb20 data-table " id="widGrid" data-widget-editbutton="false"

     data-widget-colorbutton="false"

     data-widget-editbutton="false"

     data-widget-togglebutton="false"

     data-widget-deletebutton="false"

     data-widget-fullscreenbutton="false"

     data-widget-custombutton="false"

     role="widget" style=""



    >

    <!-- widget options:

                    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">



                    data-widget-colorbutton="false"

                    data-widget-editbutton="false"

                    data-widget-togglebutton="false"

                    data-widget-deletebutton="false"

                    data-widget-fullscreenbutton="false"

                    data-widget-custombutton="false"

                    data-widget-collapsed="true"

                    data-widget-sortable="false"



                    -->

                    

                    

                    <div class="panel-heading clearfix">

                    

              <?php echo $this->translate('Settings') ?>

                    <div class="widget-toolbar">



            

        </div>

                     </div>

                    

   

    <!-- widget div-->



        <!-- widget edit box -->

        <div class="jarviswidget-editbox">

            <!-- This area used as dropdown edit box -->



        </div>

        <!-- end widget edit box -->



        <!-- widget content -->

        <di class="dataTables_wrapper no-footer">



			<div class="widget-body">

				

				<div class="row rowappliedstl">

				 	<!--<div class="col-md-12">

						<span class="list_heading">Client Report</span><hr>

					</div>--><hr>

				 	

					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('30',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('department', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-ios-briefcase liappliedsizestl iconcolororange"></i>

							</li>

							<li>

								<span>Department</span>				

							</li>

						</ul>

						</a>

						<?php } ?>

						</div>

					</div>

					
				 	<div class="col-md-2">

						<div class="columnappliedstl">

						<?php

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('31',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('designation', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-person-stalker liappliedsizestl iconcolorblue"></i>

							</li>

							<li>

								<span>Designation</span>				

							</li>

						</ul>

						</a>

						<?php } ?>

						</div>

					</div>
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('57',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('nationality', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-ios-world liappliedsizestl iconcolororange"></i>

							</li>

							<li>

								<span>Nationality</span>				

							</li>

						</ul>

						</a>

						<?php } ?>

						</div>

					</div>

				 	<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('65',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('academicyear', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-calendar liappliedsizestl iconcolorgreen"></i>

							</li>

							<li>

								<span>Academic Year</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>


				 	

					
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('19',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('acl', array('action' => 'rolesaction')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-briefcase liappliedsizestl iconcolorblue"></i>

							</li>

							<li>

								<span>Roles Setup</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>

				 	<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('21',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('permissions', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-unlocked liappliedsizestl"></i>

							</li>

							<li>

								<span>Permissions</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>

				</div>

				<div class="row rowappliedstl">
				 	
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('67',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('holiday', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-android-calendar liappliedsizestl iconcolorgreen"></i>

							</li>

							<li>

								<span>Holiday</span>				

							</li>

						</ul>

						</a>

						<?php } ?>

						</div>

					</div>
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('61',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('subject', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-ios-list liappliedsizestl iconcolorpink"></i>

							</li>

							<li>

								<span>Subject</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>
					 
				
					
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('58',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('classes', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-android-home liappliedsizestl iconcolororange"></i>

							</li>

							<li>

								<span>Class</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('59',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('section', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-ios-color-filter-outline liappliedsizestl iconcolormarun"></i>

							</li>

							<li>

								<span>Section</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('60',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('languages', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-social-css3-outline liappliedsizestl"></i>

							</li>

							<li>

								<span>Language</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>
					
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 ) {

						?>

						<a href="<?php echo $this->url('settings', array('action' => 'info')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-ios-gear liappliedsizestl iconcolorblue"></i>

							</li>

							<li>

								<span>School Settings</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>
					
					

				</div>					

								<div class="row rowappliedstl">
				 	
					
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 ) {

						?>

						<a href="<?php echo $this->url('notificationsettings', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-ios-gear liappliedsizestl"></i>

							</li>

							<li>

								<span>Notification Settings</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>
					
					<div class="col-md-2">

						<div class="columnappliedstl">

						<?php 

							if($_SESSION["ROLE_ID"] == 0 || (is_array($_SESSION['ALLOWED_MODULES_LIST']) && in_array('73',$_SESSION['ALLOWED_MODULES_LIST']))) {

						?>

						<a href="<?php echo $this->url('exam', array('action' => 'index')); ?>">

						<ul class="list-unstyled ulappliedstl">

							<li>

								<i class="ion ion-ios-paper liappliedsizestl"></i>

							</li>

							<li>

								<span>Exam</span>				

							</li>

						</ul>

						</a>

						<?php } ?>


						</div>

					</div>
					

				</div>					


			 </div>

               

        <!-- end widget content -->





    </div>

    <!-- end widget div -->



</div>

<!-- end widget -->



            

			

			<div class="jarviswidget hide panel panel-default panel-hovered panel-stacked mb30" id="widForm"

     data-widget-colorbutton="false"

     data-widget-editbutton="false"

     data-widget-togglebutton="false"

     data-widget-deletebutton="false"

     data-widget-fullscreenbutton="false"

     data-widget-custombutton="false"

     role="widget" style=""

     xmlns="http://www.w3.org/1999/html">



    <header>



        <span class="widget-icon"> <i class="glyphicon glyphicon-stats txt-color-darken"></i> </span>



        <h2>Role Info :</h2>



        <div class="widget-toolbar" style="">



        </div>



    </header>



    <!-- widget div-->

    <div class="no-padding">

        <!-- widget edit box -->

        <div class="jarviswidget-editbox">

            Username

        </div>

        <!-- end widget edit box -->



        <div class="widget-body">



            <!-- content -->









            

            



            

            <!-- end general tab pane -->



        </div>



        <!-- Start All tab pane -->



        <!-- End All tab pane -->



        <!-- end content -->

    </div>



</div>





        </article>

        <!-- WIDGET END -->



    </div>



    <!-- end row -->



    <!-- end row -->

 </div>

</section>

<!-- end widget grid -->







<script>

    // load Page related plugins





                loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/jquery.dataTables.min.js", function () {

                    loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.colVis.min.js", function () {

                        loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.tableTools.min.js", function () {

                            loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.bootstrap.min.js", function () {

                                loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)

                            });

                        });

        });

    });



</script>

