<!-- widget grid -->
<section id="widget-grid" class="page page-ui-tables">

    <!-- row -->
    <div class="row">

        <!-- NEW WIDGET START -->
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">



            <!-- Widget ID (each widget will need unique ID)-->
<div class="jarviswidget jarviswidget-color-blueDark panel panel-lined table-responsive panel-hovered mb20 data-table " id="widGrid" data-widget-editbutton="false"
     data-widget-colorbutton="false"
     data-widget-editbutton="false"
     data-widget-togglebutton="false"
     data-widget-deletebutton="false"
     data-widget-fullscreenbutton="false"
     data-widget-custombutton="false"
     role="widget" style=""

    >
    <!-- widget options:
                    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

                    data-widget-colorbutton="false"
                    data-widget-editbutton="false"
                    data-widget-togglebutton="false"
                    data-widget-deletebutton="false"
                    data-widget-fullscreenbutton="false"
                    data-widget-custombutton="false"
                    data-widget-collapsed="true"
                    data-widget-sortable="false"

                    -->
    <header>
        <span class="widget-icon"> <i class="fa fa-table"></i> </span>

        <h2><?php echo $this->translate('Home -> Role Management -> Modules List') ?></h2>


        <div class="widget-toolbar">

            <div class="btn-group">
                <button id="btnNew" class="btn dropdown-toggle btn-xs btn-primary" data-toggle="dropdown"><i
                        class="fa fa-plus"></i> <?php echo $this->translate('New') ?>
                </button>
            </div>
        </div>

    </header>

    <!-- widget div-->
    <div>

        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->

        </div>
        <!-- end widget edit box -->

        <!-- widget content -->
        <di class="dataTables_wrapper no-footer">

            <table id="tblMasterList" class="table table-striped table-bordered table-hover responsive-table" width="100%">


                <col width = "30%">
                <col width = "25%">
                <col width = "10%">

                <thead>
                <tr>
                    <th>ID</th>
					<th><i class="fa fa-fw  txt-color-blue hidden-md hidden-sm hidden-xs">
                    </i>  <?php echo $this->translate('Name'); ?></th>
                    <th><i class="fa fa-fw  txt-color-blue hidden-md hidden-sm hidden-xs">
                    </i>  <?php echo $this->translate('Description'); ?></th>
                    <th><i class=" txt-color-blue hidden-md hidden-sm hidden-xs"></i> <?php echo $this->translate('Action'); ?> </th>

                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>

        </div>
        <!-- end widget content -->


    </div>
    <!-- end widget div -->

</div>
<!-- end widget -->

            
			
			<div class="jarviswidget hide panel panel-default panel-hovered panel-stacked mb30" id="widForm"
     data-widget-colorbutton="false"
     data-widget-editbutton="false"
     data-widget-togglebutton="false"
     data-widget-deletebutton="false"
     data-widget-fullscreenbutton="false"
     data-widget-custombutton="false"
     role="widget" style=""
     xmlns="http://www.w3.org/1999/html">

    <header>

        <span class="widget-icon"> <i class="glyphicon glyphicon-stats txt-color-darken"></i> </span>

        <h2>Module Info :</h2>

        <div class="widget-toolbar" style="">

        </div>

    </header>

    <!-- widget div-->
    <div class="no-padding">
        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            Username
        </div>
        <!-- end widget edit box -->

        <div class="widget-body">

            <!-- content -->

            <div class="widget-toolbar" style="padding-right: 10px;padding-left: 10px">
                <a id="btnBack" href="javascript:void(0);" class="btn btn-xs btn-default"><i
                        class="fa fa-arrow-left"></i> <span
                        class="hidden-mobile hidden-tablet">Back</span> </a>
                <button id="btnSave" type="submit" class="btn btn-xs btn-success"><i class="fa fa-save"></i>
                    <strong><span
                            class="hidden-mobile hidden-tablet">Save</span> </strong></button>

            </div>
            <ul class="nav nav-tabs  in" id="myTabMaster">
                <li class="active">
                    <a data-toggle="tab" href="#general"><i class="fa fa-lg fa-info-circle"></i> <span
                            class="hidden-mobile hidden-tablet">General</span></a>
                </li>
            </ul>

            <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade active in padding-10 no-padding-bottom" id="general">
                    <form id="frmForm" class="smart-form" novalidate="novalidate" enctype="multipart/form-data">
                        <fieldset style="padding-top: 5px">
                            <div class="row">						
								

                                <section class="col col-4">
                                    <label class="label"><strong class="txt-color-blue"><?php echo $this->translate('Name'); ?></strong><span class="txt-color-red"> *</span></label>
                                    <label class="input"> <i class="  "></i>
                                        <input type="text" id="module_name" name="module_name" class=" ">
                                    </label>
                                </section>
								
								<section class="col col-4">

                                    <label class="label"><strong class="txt-color-blue"><?php echo $this->translate('Description'); ?></strong></label>

                                    <label class="textarea"> <i class=""></i>

                                        <textarea type="textarea" rows="3" class=" " placeholder="Description" name="module_description" id="module_description"></textarea>



                                    </label>

                                </section>



                            </div>
                            					

               			</fieldset>
                </form>

                </div>
            </div>
            <!-- end general tab pane -->

        </div>

        <!-- Start All tab pane -->

        <!-- End All tab pane -->

        <!-- end content -->
    </div>

</div>


        </article>
        <!-- WIDGET END -->

    </div>

    <!-- end row -->

    <!-- end row -->

</section>
<!-- end widget grid -->


<script type="text/javascript">


    $(document).ready(function () {

        $("#btnSave").click(function (e) {
            e.stopPropagation();

            $("#frmForm").submit();
        });


        //Form Submission
        $("#frmForm").validate(
            {
                submitHandler: function (form) {


                    if ($("#module_name").val() == '') {
                        mySmallAlert('Error...!', 'Module name is Required', 0);
                        return;
                    }

                    if(strActionMode=="ADD") {
                        //Validate  duplicate
                        var isDuplicate = fn_validate_duplicate($("#module_name").val(), "tbl_modules", "module_name", "<?php echo $this->url('acl', array('action'=>'validateduplicate'));?>");
                        if (isDuplicate) {
                            mySmallAlert('Duplicate Error...!', 'Duplicate Found. Module name is Already exists !', 0);
                            return false;
                        }
                    }                    
                   
                    var $form = $('#frmForm');
                    var objMasterData = $form.serializeObject();
                    if (strActionMode == 'ADD')
                        $.extend(objMasterData, { MASTER_KEY_ID: 0});
                    else
                        $.extend(objMasterData, { MASTER_KEY_ID: iActiveID});

                    objMasterData = JSON.stringify(objMasterData);

                    var objFormData =
                    {
                        pAction    : strActionMode,
                        FORM_DATA: objMasterData

                    };
                    var objMyPost = AJAX_Post("<?php echo $this->url('acl', array('action'=>'moduleSave'));?>", objFormData);
                    if (objMyPost.ERR_NO === 0) {
                        if (objMyPost.DATA.DBStatus === 'OK') {
                            strActionMode = "EDIT";
                            mySmallAlert('Save Record', 'Module Entry Saved successfully', 1);
                            iActiveID = objMyPost.DATA.MY_ID;
                            visibleControl('widForm', false);
                            visibleControl('widGrid', true);
                            oTable.fnDraw();
                        }
                    }
                    else {
                        mySmallAlert('Error...!', 'There was an error', 0);
                    }

                }
            });



    });



    // PAGE RELATED SCRIPTS

    /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // locations widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

//    pageSetUp();

    /*
     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
     * eg alert("my home function");
     *
     * var pagefunction = function() {
     *   ...
     * }
     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
     *
     * TO LOAD A SCRIPT:
     * var pagefunction = function (){
     *  loadScript(".../plugin.js", run_after_loaded);
     * }
     *
     * OR
     *
     * loadScript(".../plugin.js", run_after_loaded);
     */


    // pagefunction
    var pagefunction = function () {
        //console.log("cleared");


        /* // DOM Position key index //

         l - Length changing (dropdown)
         f - Filtering input (search)
         t - The Table! (datatable)
         i - Information (records)
         p - Pagination (paging)
         r - pRocessing
         < and > - div elements
         <"#id" and > - div with an id
         <"class" and > - div with a class
         <"#id.class" and > - div with an id and class

         Also see: http://legacy.datatables.net/usage/features
         */

        /* BASIC ;*/
        var responsiveHelper_dt_basic = undefined;
        var responsiveHelper_datatable_fixed_column = undefined;
        var responsiveHelper_datatable_col_reorder = undefined;
        var responsiveHelper_datatable_tabletools = undefined;

        var breakpointDefinition = {
            tablet: 1024,
            phone: 480
        };

        /* TABLETOOLS */
        oTable = $("#tblMasterList").dataTable(
            {
                "bAutoWidth": false,
                "bLengthChange": false,
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "bProcessing": true,
                "bServerSide": true,


                "autoWidth" : true,
                "preDrawCallback" : function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#tblMasterList'), breakpointDefinition);
                    }
                },
                "rowCallback" : function(nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback" : function(oSettings) {
                    responsiveHelper_dt_basic.respond();
                },


                "fnServerParams": function (aoData) {
                    aoData.push({ "name": "id", "value": "" });
                },
                "sAjaxSource": "<?php echo $this->url('acl', array('action'=>'moduleList'));?>",
                "aoColumns": [
                    { "bSearchable": false, "bVisible": false },
                    null,
                    null,
                    {"bSearchable": false, "bSortable": false,
                        "mRender" : function (data, type, full) {

                            return grid_buttons(full[0]);

                        }
                    }
                ],
                "columnDefs": [
                    { className: "hidden", "targets": [ 0 ] }
                ]
            });

        /* END TABLETOOLS */

        fnEdit("<?php echo $this->url('acl', array('action'=>'getModulerec'));?>");
        fnView("<?php echo $this->url('acl', array('action'=>'getModulerec'));?>");
        fnDelete("<?php echo $this->url('acl', array('action'=>'moduleDelete'));?>");


    };



</script>

<script>
    // load Page related plugins


                loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/jquery.dataTables.min.js", function () {
                    loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.colVis.min.js", function () {
                        loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.tableTools.min.js", function () {
                            loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.bootstrap.min.js", function () {
                                loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)
                            });
                        });
        });
    });

</script>
