<style>
.panel-heading .help
{
	font-size:22px;
	color:#0998cd;
	margin-left:10px;
	cursor:pointer;
	
}
</style><!-- widget grid -->

<section id="widget-grid" class="page page-ui-tables">



    <!-- row -->

    <div class="row">



        <!-- NEW WIDGET START -->

        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">







            <!-- Widget ID (each widget will need unique ID)-->

<div class="jarviswidget jarviswidget-color-blueDark panel panel-lined table-responsive panel-hovered mb20 data-table " id="widGrid" data-widget-editbutton="false"

     data-widget-colorbutton="false"

     data-widget-editbutton="false"

     data-widget-togglebutton="false"

     data-widget-deletebutton="false"

     data-widget-fullscreenbutton="false"

     data-widget-custombutton="false"

     role="widget" style=""



    >

    <!-- widget options:

                    usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">



                    data-widget-colorbutton="false"

                    data-widget-editbutton="false"

                    data-widget-togglebutton="false"

                    data-widget-deletebutton="false"

                    data-widget-fullscreenbutton="false"

                    data-widget-custombutton="false"

                    data-widget-collapsed="true"

                    data-widget-sortable="false"



                    -->

                    

                    

                    <div class="panel-heading clearfix">
						  <div class="row">
							 <div class="col-md-9"><a href="<?php echo $this->url('administration', array('action' => 'index')); ?>"><?php echo $this->translate('Settings') ?></a> <?php echo $this->translate(' | Roles List') ?><i class="ion ion-help-circled help" title="help"></i></div>
							 <div class="col-md-3"><button id="btnNew" type="button" class="btn btn-primary pull-right addEventBtn waves-effect" data-toggle="dropdown" style="display: block;"><i class="ion ion-plus"></i>New</button></div>
						  </div>
					   </div>

   

    <!-- widget div-->

    



        <!-- widget edit box -->

        <div class="jarviswidget-editbox">

            <!-- This area used as dropdown edit box -->



        </div>

        <!-- end widget edit box -->



        <!-- widget content -->

        <div class="dataTables_wrapper no-footer">



            <table id="tblMasterList" class="table table-striped table-bordered table-hover responsive-table" width="100%">





                <col width = "10%">

                <col width = "10%">

                <col width = "1%">



                <thead>

                <tr>

                    <th>ID</th>

					<th><i class="fa fa-fw  txt-color-blue hidden-md hidden-sm hidden-xs">

                    </i>  <?php echo $this->translate('Name'); ?></th>

                    <th><i class="fa fa-fw  txt-color-blue hidden-md hidden-sm hidden-xs">

                    </i>  <?php echo $this->translate('Description'); ?></th>


                    <th><i class=" txt-color-blue hidden-md hidden-sm hidden-xs"></i> <?php echo $this->translate('Action'); ?> </th>


                </tr>

                </thead>

                <tbody>



                </tbody>

            </table>



        

        <!-- end widget content -->





    </div>

    <!-- end widget div -->



</div>

<!-- end widget -->



            

			

			<div class="jarviswidget hide panel panel-default panel-hovered panel-stacked mb30" id="widForm"

     data-widget-colorbutton="false"

     data-widget-editbutton="false"

     data-widget-togglebutton="false"

     data-widget-deletebutton="false"

     data-widget-fullscreenbutton="false"

     data-widget-custombutton="false"

     role="widget" style=""

     xmlns="http://www.w3.org/1999/html">

     

     

     <div class="panel-heading clearfix">

   Role Info

    

    

   <div class="right col-lg-3 col-xs-12 mp0 frm">

   <button id="btnSave" type="submit" class="right btn btn-success btn-icon-inline btn-sm mb15 addEventBtn">

   <i class="fa fa-floppy-o"></i>Save

   </button>

   <button id="btnBack" type="button" class="right btn btn-default btn-icon-inline btn-sm mb15 addEventBtn">

   <i class="ion ion-arrow-left-c"></i>Back

   </button>

   

   

   </div>

    

    

    </div>

    

    

    <!-- widget div-->

    <div class="panel-body">

        <!-- widget edit box -->

        <!--<div class="jarviswidget-editbox">

            Username

        </div>-->

        <!-- end widget edit box -->



        <div class="widget-body">



            <!-- content -->

<!--

            <ul class="nav nav-tabs  in" id="myTabMaster">

                <li class="active">

                    <a data-toggle="tab" href="#general"><i class="fa fa-lg fa-info-circle"></i> <span

                            class="hidden-mobile hidden-tablet">General</span></a>

                </li>

            </ul>-->



            <div id="myTabContent">

                <div class="tab-pane fade active in padding-10 no-padding-bottom" id="general">

                    <form id="frmForm" class="smart-form" novalidate="novalidate" enctype="multipart/form-data">

                        <fieldset style="padding-top: 5px">

                           <div class="panel panel-default panel-hovered panel-stacked mb30">

      <div class="panel-body">

                            <div class="row">						

								<div class="col-md-6">



                                <section class="form-group form-group-sm clearfix">

                                    <label class="col-md-3 col-sm-3 col-xs-12 control-label"><strong class="txt-color-blue"><?php echo $this->translate('Name'); ?></strong><span class="txt-color-red"> *</span></label>

                                    <label class="col-md-9 col-sm-9 col-xs-12"> 

                                        <input type="text" id="role_name" name="role_name" class="form-control " placeholder="<?php echo $this->translate('Name'); ?>">

                                    </label>

                                </section>

                             </div>

                             <div class="col-md-6">

								<section class="form-group form-group-sm clearfix">



                                    <label class="col-md-3 col-sm-3 col-xs-12 control-label"><strong class="txt-color-blue"><?php echo $this->translate('Description'); ?></strong></label>



                                    <label class="col-md-9 col-sm-9 col-xs-12">



                                        <textarea type="textarea" rows="3" class="form-control " placeholder="Description" name="role_description" id="role_description"></textarea>







                                    </label>



                                </section>



                             </div>



                            </div>

                            </div>

                         </div>				



               			</fieldset>

                </form>



                </div>

            </div>

            <!-- end general tab pane -->



        </div>



        <!-- Start All tab pane -->



        <!-- End All tab pane -->



        <!-- end content -->

    </div>



</div>





        </article>

        <!-- WIDGET END -->



    </div>



    <!-- end row -->



    <!-- end row -->



</section>

<!-- end widget grid -->





<script type="text/javascript">





    $(document).ready(function () {

		acl_PRINT=0;


		$('.help').click(function(){
			$('#video_modal').modal({backdrop: 'static', keyboard: false});
		});
        $("#btnSave").click(function (e) {

            e.stopPropagation();



            $("#frmForm").submit();

        });





        //Form Submission

        $("#frmForm").validate(

            {

                submitHandler: function (form) {





                    if ($("#role_name").val() == '') {

                        mySmallAlert('Error...!', 'Role name is Required', 0);

                        return;

                    }



                    if(strActionMode=="ADD") {

                        //Validate  duplicate

                        var isDuplicate = fn_validate_duplicate($("#role_name").val(), "tbl_roles", "role_name", "<?php echo $this->url('acl', array('action'=>'validateduplicate'));?>");

                        if (isDuplicate) {

                            mySmallAlert('Duplicate Error...!', 'Duplicate Found. Role name is Already exists !', 0);

                            return false;

                        }

                    }                    

                   

                    var $form = $('#frmForm');

                    var objMasterData = $form.serializeObject();

                    if (strActionMode == 'ADD')

                        $.extend(objMasterData, { MASTER_KEY_ID: 0});

                    else

                        $.extend(objMasterData, { MASTER_KEY_ID: iActiveID});



                    objMasterData = JSON.stringify(objMasterData);



                    var objFormData =

                    {

                        pAction    : strActionMode,

                        FORM_DATA: objMasterData



                    };

                    var objMyPost = AJAX_Post("<?php echo $this->url('acl', array('action'=>'roleSave'));?>", objFormData);

                    if (objMyPost.ERR_NO === 0) {

                        if (objMyPost.DATA.DBStatus === 'OK') {

                            strActionMode = "EDIT";

                            mySmallAlert('Save Record', 'Role Entry Saved successfully', 1);

                            iActiveID = objMyPost.DATA.MY_ID;

                            visibleControl('widForm', false);

                            visibleControl('widGrid', true);

                            oTable.fnDraw();

                        }

                    }

                    else {

                        mySmallAlert('Error...!', 'There was an error', 0);

                    }



                }

            });







    });







    // PAGE RELATED SCRIPTS



    /* DO NOT REMOVE : GLOBAL FUNCTIONS!

     *

     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS

     *

     * // activate tooltips

     * $("[rel=tooltip]").tooltip();

     *

     * // activate popovers

     * $("[rel=popover]").popover();

     *

     * // activate popovers with hover states

     * $("[rel=popover-hover]").popover({ trigger: "hover" });

     *

     * // activate inline charts

     * runAllCharts();

     *

     * // locations widgets

     * setup_widgets_desktop();

     *

     * // run form elements

     * runAllForms();

     *

     ********************************

     *

     * pageSetUp() is needed whenever you load a page.

     * It initializes and checks for all basic elements of the page

     * and makes rendering easier.

     *

     */



//    pageSetUp();



    /*

     * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE

     * eg alert("my home function");

     *

     * var pagefunction = function() {

     *   ...

     * }

     * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);

     *

     * TO LOAD A SCRIPT:

     * var pagefunction = function (){

     *  loadScript(".../plugin.js", run_after_loaded);

     * }

     *

     * OR

     *

     * loadScript(".../plugin.js", run_after_loaded);

     */





    // pagefunction

    var pagefunction = function () {

        //console.log("cleared");





        /* // DOM Position key index //



         l - Length changing (dropdown)

         f - Filtering input (search)

         t - The Table! (datatable)

         i - Information (records)

         p - Pagination (paging)

         r - pRocessing

         < and > - div elements

         <"#id" and > - div with an id

         <"class" and > - div with a class

         <"#id.class" and > - div with an id and class



         Also see: http://legacy.datatables.net/usage/features

         */



        /* BASIC ;*/

        var responsiveHelper_dt_basic = undefined;

        var responsiveHelper_datatable_fixed_column = undefined;

        var responsiveHelper_datatable_col_reorder = undefined;

        var responsiveHelper_datatable_tabletools = undefined;



        var breakpointDefinition = {

            tablet: 1024,

            phone: 480

        };



        /* TABLETOOLS */

        oTable = $("#tblMasterList").dataTable(

            {

                "bAutoWidth": false,

                "bLengthChange": false,

                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>" +

                    "t" +

                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",

                "bProcessing": true,

                "bServerSide": true,





                "autoWidth" : true,

                "preDrawCallback" : function() {

                    // Initialize the responsive datatables helper once.

                    if (!responsiveHelper_dt_basic) {

                        responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#tblMasterList'), breakpointDefinition);

                    }

                },

                "rowCallback" : function(nRow) {

                    responsiveHelper_dt_basic.createExpandIcon(nRow);

                },

                "drawCallback" : function(oSettings) {

                    responsiveHelper_dt_basic.respond();

                },





                "fnServerParams": function (aoData) {

                    aoData.push({ "name": "id", "value": "" });

                },

                "sAjaxSource": "<?php echo $this->url('acl', array('action'=>'roleList'));?>",

                "aoColumns": [

                    { "bSearchable": false, "bVisible": false },

					
					null,

                    null,
					
                    {"bSearchable": false, "bSortable": false,

                        "mRender" : function (data, type, full) {


							if(full[1] == 'Teacher' || full[1] == 'Parents' || full[1] == 'Staff')

							{

								acl_DELETE="0";
								acl_EDIT="0";
								
							}

							else

							{

								acl_DELETE="1";
								acl_EDIT="1";

							}


                            return grid_buttons(full[0]);



                        }

                    }
					

                    

                ],

                "columnDefs": [

                    { className: "hidden", "targets": [ 0 ] }

                ]

            });



        /* END TABLETOOLS */

		$('.dataTables_filter input').attr("placeholder", "Search");
		//$(".dataTables_filter label").addClass('right');


        //fnEdit("<?php echo $this->url('acl', array('action'=>'getRolerec'));?>");

        //fnView("<?php echo $this->url('acl', array('action'=>'getRolerec'));?>");

        //fnDelete("<?php echo $this->url('acl', array('action'=>'roleDelete'));?>");



		fnDelete("<?php echo $this->url('acl', array('action'=>'roleDelete'));?>");



        var strUrl = "<?php echo $this->url('acl', array('action'=>'getRolerec'));?>";



        //Function Used for Edit



        oTable.delegate('a.edit', 'click', function (e) {



            e.preventDefault();





            //objMyDetailRecords.length = 0;



            //tblDetailsListBody.html('');



            /*



             var nRow = $(this).parents('tr')[0];



             var aData = oTable.fnGetData(nRow);



             iActiveID = parseInt(aData[0]);



             */



            iActiveID = $(this).attr("row-id");



			

            //empty the form fields



            clearForm("frmForm");



            cPopulateEditEntries(iActiveID, strUrl);



            glbControlEnable(true);



        });





        //Function Used for View



        oTable.delegate('a.view', 'click', function (e) {



            e.preventDefault();





            objMyDetailRecords.length = 0;



            tblDetailsListBody.html('');



            /*



             var nRow = $(this).parents('tr')[0];



             var aData = oTable.fnGetData(nRow);



             iActiveID = parseInt(aData[0]);



             */



            iActiveID = $(this).attr("row-id");





            //empty the form fields



            clearForm("frmForm");



            cPopulateEditEntries(iActiveID, strUrl);



            glbControlEnable(false);



        });

		

    };







</script>



<script>

    // load Page related plugins





                loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/jquery.dataTables.min.js", function () {

                    loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.colVis.min.js", function () {

                        loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.tableTools.min.js", function () {

                            loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatables/dataTables.bootstrap.min.js", function () {

                                loadScript("<?php echo $this->basePath();?>/public/v1.6.1/js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)

                            });

                        });

        });

    });

	

	//------------------- populate edit entries-----------------------------------------------------------------------------



    function cPopulateEditEntries(iID,strURL) {

        iActiveID = iID;



        var arrForms=[]; // Keep Form Values

        var strElementType; // Keep element type



        var objFormData =

        {

            pAction: 'GETREC',

            KEY_ID : iActiveID

        };

        var objMyPost = AJAX_Post(strURL, objFormData);

		

        if (objMyPost.ERR_NO === 0) {

            if (objMyPost.DATA.DBStatus === 'OK') {



                visibleControl('widForm', true);

                visibleControl('widGrid', false);

                strActionMode = 'EDIT';



                //populate master Records



                arrForms=objMyPost.DATA.data[0];

                $.each( arrForms, function( key, value ) { 





                    if ($("#"+key).length > 0) {  // check if exists or not



                        strElementType= $("#"+key).attr("type");

					

                        if(strElementType == "hidden") {  // if textbox

                            $("#" + key).val(value);

                            $("#spanRefNo").html(value);

                        }

                        else  if(strElementType == "text") {  // if textbox

                            $("#" + key).val(value);

                        }

                        else if($("#"+key).attr("name") == "role_description") {  // if textarea

                            $("textarea#"+key).text(value);

                        }

                        else if(strElementType == "select") {  // if Select Box							

                            $("#" + key).select2("val",value);

                        }

                        else if(strElementType == "multiselect") {  // if Select Box with multi select

                            var arrValues = $.parseJSON(stripslashes(value));

                            $("#" + key).select2("val", arrValues);

                        }

                    }

                });

				

            }

        }

        else {

            mySmallAlert('Error...!', 'There was an error', 0);

        }

    }

	

</script>
<div id="video_modal" class="modal fade bs-example-modal-md">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h4 class="modal-title">MSPEDUCARE Roles List Module</h4>
					</div>
					
					<div class="modal-body customsrolling">	
					
						  <div class="row">
<iframe width="560" height="315" src="https://www.youtube.com/embed/ehCnqukVieU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
						  </div>

                     </div>	
					 <div class="modal-footer">
						
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>  
             </div>
                     
		</div>	
		
</div>
